files:
  checkpoint: r50_1x_sk1.pth
  images_path: /Users/giannis/datasets/ILSVRC2012_img_val
  labels_path: /Users/giannis/datasets/ILSVRC2012_validation_ground_truth.txt
  mappings_path: null

device: 'cpu'

evaluate:
  top_k: 1
  batch_size: 64

train:
  epochs: 200
  batch_size: 512
  optimizer:
    lr: 0.0002
    beta1: 0.8
    beta2: 0.999
    scheduler: const
    weight_decay: 1e-06
